[package]
name = "mp3man"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.16.0", default-features = false, features = ['termion']}
termion = "1.5.6"
rodio = "0.14.0"
